server:
  port: 9999
http:
  basic:
    user: test
    password: test
    
zuul:
  ratelimit:
    enabled: true
    key-prefix: demo-app
    repository: REDIS
    behind-proxy: true
#    default-policy-list:
#      - limit: 2
#        quota: 1000
#        refresh-interval: 120
#        type:
#          - user
#          - origin
#          - url
    policy-list:
      api-a:
        - limit: 2
          quota: 1000
          refresh-interval: 120
          type:
            - user
            - origin
            - url
  routes:
    api-a:
      path: /api/a/**
      url: forward:/
    api-b:
      path: /api/b/**
      url: forward:/b
spring:
  redis:
    database: 6
    host: 60.205.219.176
    port: 6390
    password: Jlm4Temnn0awl
    jedis:
      pool:
        max-idle: 10
        min-idle: 1
        max-wait: 60s
    timeout: 20s